"""Export packaging.

Turns generated source into the deliverables the export dialog offers: a single
file, a full project ZIP (sources + project JSON + theme + README), or the raw
JSON documents on their own.
"""

from __future__ import annotations

import io
import json
import zipfile
from datetime import datetime, timezone

from generators.base import GenerationResult, GeneratorInfo
from models.schema import Project


def project_json(project: Project) -> str:
    return project.model_dump_json(indent=2, by_alias=True)


def theme_json(project: Project) -> str:
    return project.theme.model_dump_json(indent=2, by_alias=True)


def build_zip(project: Project, result: GenerationResult, info: GeneratorInfo,
              *, include_project: bool = True, include_theme: bool = True,
              include_assets: bool = True) -> bytes:
    """Package a generation result as a downloadable ZIP archive."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for generated in result.files:
            archive.writestr(f"src/{generated.path}", generated.content)

        archive.writestr("README.md", _readme(project, result, info))

        if include_project:
            archive.writestr("project.guiforge.json", project_json(project))
        if include_theme:
            archive.writestr("theme.json", theme_json(project))
        if include_assets and project.assets:
            for name, data_uri in project.assets.items():
                payload = _decode_data_uri(data_uri)
                if payload is not None:
                    archive.writestr(f"assets/{name}", payload)

        if result.diagnostics:
            archive.writestr("GENERATION_NOTES.txt", _notes(result))

    return buffer.getvalue()


def _readme(project: Project, result: GenerationResult, info: GeneratorInfo) -> str:
    entry = result.entry.path if result.entry else "src/main.py"
    run_command = (f"python src/{entry}" if info.language == "python"
                   else "See your build system for compiling the generated sources.")
    files = "\n".join(f"- `src/{f.path}` ({f.line_count} lines)" for f in result.files)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""# {project.project.name}

{project.project.description or "Generated by GUIForge."}

- **Framework:** {info.label} ({info.language_label})
- **Generated:** {generated_at}
- **Window:** {project.window.width}x{project.window.height}

## Files

{files}
- `project.guiforge.json` - reopen this in GUIForge to keep editing the design
- `theme.json` - design tokens, importable into another project

## Running

```
{run_command}
```

## Regenerating

Open `project.guiforge.json` in GUIForge, edit the design, and export again.
Application logic belongs in your own modules — the generated UI file is
overwritten on every export.
"""


def _notes(result: GenerationResult) -> str:
    lines = ["Generation notes", "=" * 16, ""]
    for diagnostic in result.diagnostics:
        widget = f" [{diagnostic.widget_id}]" if diagnostic.widget_id else ""
        lines.append(f"{diagnostic.level.upper()}{widget}: {diagnostic.message}")
    return "\n".join(lines) + "\n"


def _decode_data_uri(value: str) -> bytes | None:
    """Assets are stored as data URIs so a project file stays self-contained."""
    import base64

    if not value.startswith("data:"):
        return value.encode("utf-8")
    try:
        header, payload = value.split(",", 1)
        return base64.b64decode(payload) if ";base64" in header else payload.encode("utf-8")
    except (ValueError, base64.binascii.Error):  # type: ignore[attr-defined]
        return None


def bundle_json(project: Project) -> str:
    """The `.guiforge` document plus a manifest, for the JSON export option."""
    return json.dumps(
        {
            "kind": "guiforge.project",
            "exportedAt": datetime.now(timezone.utc).isoformat(),
            "document": json.loads(project_json(project)),
        },
        indent=2,
    )
